compressionLevel: mixed

enableGlobalCache: false

enableHardenedMode: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: "7d"

npmPreapprovedPackages:
  - "defu"

yarnPath: .yarn/releases/yarn-4.13.0.cjs
